---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qp
  description: provided a user defined function, qp passes each message in a queue through that function
  annotations:
    github.com/project-slug: honestbank/qp
    sonarqube.org/project-key: honestbank_qp
  tags:
    - golang
    - user:cyberhck
spec:
  type: library
  lifecycle: production
  owner: spend-squad
  dependsOn: 
    - component:backoff-policy
